services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '2717:27017'
    volumes:
      - chat-app-db:/data/db
      - chat-app-config:/data/configdb
    container_name: 'community-chat-app'
volumes:
  chat-app-db:
  chat-app-config:
