services:
    app:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/src/app
        container_name: 'api-project'
        environment:
            - REDIS_HOST=blog-community-redis
            - REDIS_PORT=6379

            - MONGO_HOST=blog-community-mongo
            - DB_USER=root
            - DB_PASS=example
            - DB_PORT=27017
            - DB_NAME=community-chat-app

        depends_on:
            - redis-cache
            - mongo-db
        networks:
            - blog-community-network

    mongo-db:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - '2717:27017'
        volumes:
            - blog-community-mongo_db:/data/db
            - blog-community-mongo_config:/data/configdb
        container_name: 'blog-community-mongo'
        networks:
            - blog-community-network

    redis-cache:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        container_name: 'blog-community-redis'
        volumes:
            - blog-community-redis_cache:/data
        networks:
            - blog-community-network

volumes:
    blog-community-mongo_db:
    blog-community-mongo_config:
    blog-community-redis_cache:

networks:
    blog-community-network: