services:
    app:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/src/app
        container_name: 'api-project'
        depends_on:
            - mongo-db
            - redis-cache

    mongo-db:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - '2717:27017'
        volumes:
            - blog-community-mongo_db:/data/db
            - blog-community-mongo_config:/data/configdb
        container_name: 'blog-community-mongo'

    redis-cache:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        container_name: 'blog-community-redis'
        volumes:
            - blog-community-redis_cache:/data

volumes:
    blog-community-mongo_db:
    blog-community-mongo_config:
    blog-community-redis_cache:
